#### PARAMETERS ####

# How many parents do you want in each generation? TYPE: int
parents : 2500

# How many generations do you want the algorithm to run through? TYPE: int
generations : 400

# What are the probabilities you want for crossover, mutation and individual mutation respectively? TYPE: int, TYPE: int, TYPE: int
# Probabilities must sum to less than 1!
crossover : 0.7
mutation : 0.2
individual mutation : 0.05

# What are the desired weightings for the objectives? TYPE: list
# [sch, park, med, super, activ, tsu, cflood, rflood, liq, dev] (len=10)
weightings : [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
# Give a name to the Weighting Scheme. e.g. 'Balanced' TYPE: str
w_scheme : 'Balanced'

# How many dwellings are projected for future growth of the city? TYPE: int
req_dwellings : 50000
# Give a name to the Dwelling Scheme. e.g. 'High' TYPE: str
d_scheme : 'High'

# Enter up to 8 acceptable densities for development. TYPE: list
# Units of dwellings per hectare
densities : [83, 92, 111, 133]

# Define the minimum and maximum densities statistical areas are allowed to be developed within. TYPE: int, TYPE: int
# Units of dwellings per hectare
# min and max must be smaller and larger than all the values given in the above list respectively
min_density : 25
max_density : 140

# How often (in generations) shall the spatial plans be plotted? TYPE: int
step_size : 100


#### DATA ####

# Path to census data. TYPE: str
census_fp : r'data/christchurch/raw/census-dwellings.shp'

# Path to city boundary shapefile. TYPE: str
boundary_fp : r'data/christchurch/raw/urban_extent.shp'

# Path to constaints data. TYPE: str
constraints_fp : r'data/christchurch/pre_processed/constraints.shp'

# Paths to the shapefiles for the built in objective functions. TYPE: str
# Leave blank if you do not wish to evaluate this objective
schools_fp : ''
parks_fp : r'data/christchurch/pre_processed/parks.shp'
clinics_fp : ''
supermarkets_fp : ''
malls_fp : r'data/christchurch/pre_processed/malls.shp'
